apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp  # Doit correspondre à l'étiquette dans le déploiement
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000        # Le port interne du service dans Kubernetes
    targetPort: 3000   # Le port exposé par ton conteneur Node.js
    nodePort: 31110    # Le port externe sur lequel tu peux accéder depuis l'extérieur

